version: '3.5'

services:
  osrm:
    container_name: bsc_osrm
    build:
      context: ./docker/osrm
    volumes:
    - ./data:/data
    user: ${USER}:${GROUP}
  busstopchecker:
    container_name: bsc_node
    build:
      context: ./docker/busstopchecker
    volumes:
      - ./data:/data
      - ./:/app
    environment:
      - PGHOST=bsc_postgres
      - PGUSER=bsc
      - PGPASSWORD=bsc
      - PGDATABASE=bsc
    user: ${USER}:${GROUP}
    links:
      - postgres
  postgres:
    container_name: bsc_postgres
    command: postgres -c 'max_connections=500' -c 'max_wal_size=5GB' -c 'synchronous_commit=off' -c 'fsync=off' -c 'wal_buffers=32MB' -c 'shared_buffers=5GB' -c 'work_mem=2GB'  -c 'maintenance_work_mem=2GB' -c 'effective_io_concurrency=30'
    image: mdillon/postgis:11-alpine
    ports:
      - "5432"
    restart: always
    environment:
      - POSTGRES_USER=bsc
      - POSTGRES_PASSWORD=bsc
      - POSTGRES_DB=bsc
    volumes:
      - bsc_postgres:/var/lib/postgresql/data:z,delegated
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  bsc_postgres:
